### PR TITLE
[util] Shorten blog title & zoom out logo size

### PR DESCRIPTION
**Pull request by ComMouse**
Since the long title will contribute to mess layout on mobile clients, I have made it shorter.

@gaocegege @at15 @arrowrowe @JasonQSY

### CODE REVIEW

**Comment by arrowrowe** [comment]
贴个效果图对比?

**Comment by ComMouse** [comment]
image

**Comment by gaocegege** [comment]
Hardcode, OK...
LGTM

[Approved with PullApprove](https://pullapprove.com/dyweb/blog/pull-request/11/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=dyweb/blog) [Approved with PullApprove](https://pullapprove.com/dyweb/blog/pull-request/11/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=dyweb/blog)

**Review by JasonQSY — APPROVED** [review]
LGTM

**Comment by at15** [comment]
LGTM

**Comment by at15** [comment]
LGTM   忘了加`![LGTM]`的正则了....

[Approved with PullApprove](https://pullapprove.com/dyweb/blog/pull-request/11/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=dyweb/blog) [Approved with PullApprove](https://pullapprove.com/dyweb/blog/pull-request/11/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=dyweb/blog)

**Pull request merged**
