### PR TITLE
[post][tsdb-intro] Init Introduction to TSDB

### PR DESCRIPTION
**Pull request by at15**
Related issue #16 

## Post info

- Title: Introduction to Time Series Database
- Author: @at15
- License: default
- Estimate finish time: 07/15/2017

## Related projects

- [Awesome Time Series Database](https://github.com/xephonhq/awesome-time-series-database) An awesome list for time series databases by @at15
- [Xephon-K](https://github.com/xephonhq/xephon-k) A time series database with multiple backends by @at15

### CODE REVIEW

**Comment by at15** [comment]
travis broke on Go 1.6 due to `go get ink` https://travis-ci.org/dyweb/blog/jobs/251611860 cc @gaocegege  maybe we should remove Go 1.6 from travis?

**Comment by gaocegege** [comment]
Removing Go 1.6 looks good to me

**Comment by gaocegege** [comment]
The PR is WIP, if you finish, at me to review :)

**Comment by at15** [comment]
今天晚上开始填坑..... 话说东岳要不弄个知乎的专栏 cc @gaocegege @mrmiywj @xplorld

**Comment by gaocegege** [comment]
专栏写啥？你写还是我写？

**Comment by at15** [comment]
我只是想 @gaocegege 把东岳 blog 的转过去 .... 否则估计也没什么人看 ... 写只能你写，我知乎手机没验证，收藏都不行了 /w\

**Comment by gaocegege** [comment]
（微笑

**Comment by gaocegege** [comment]
等你写完了我再 review

**Comment by gaocegege** [comment]
https://zhuanlan.zhihu.com/dongyue

**Comment by gaocegege** [comment]
催更了催更了！

**Comment by at15** [comment]
@gaocegege 英文版写完了可以看下了 .... @arrowrowe 帮忙看下中文版的标点，虽然还没写完，thx

**Comment by at15** [comment]
都写完了 ... cc @gaocegege @arrowrowe @JasonQSY  我先去 ... (最近好像没啥游戏玩....

**Comment by JasonQSY** [comment]
Factorio @at15

**Comment by gaocegege** [comment]
LGTM, boy

[Approved with PullApprove](https://pullapprove.com/dyweb/blog/pull-request/17/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=dyweb/blog)

**Comment by at15** [comment]
LGTM

[Approved with PullApprove](https://pullapprove.com/dyweb/blog/pull-request/17/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=dyweb/blog)

**Pull request merged**
